# Generated by Django 5.2.13 on 2026-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='skills'),
        ),
    ]
