# Generated by Django 5.2.13 on 2026-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bloguser_bio_bloguser_location_bloguser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='avatar'),
        ),
    ]
