# Generated by Django 5.2.13 on 2026-05-03 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='avatar',
            field=models.ImageField(blank=True, help_text='右侧侧边栏显示的个人头像', null=True, upload_to='avatar/', verbose_name='管理员头像'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='网站全局背景图片', null=True, upload_to='background/', verbose_name='背景图片/壁纸'),
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(help_text='保存到 D:\\LLLblog\\attachments\\', upload_to='attachments/', verbose_name='文件')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '文章附件',
                'verbose_name_plural': '文章附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
