# Generated by Django 5.2.13 on 2026-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogsettings_avatar_blogsettings_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='analytics_code',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='网站统计代码'),
        ),
    ]
