# Generated by Django 5.2.13 on 2026-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogsettings_analytics_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='在侧边栏展示的个人简介', max_length=500, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='personal_website',
            field=models.URLField(blank=True, default='', null=True, verbose_name='个人网站'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='用逗号分隔的技能，如: Python,Django,React', max_length=500, null=True, verbose_name='技能标签'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='网站全局背景图片(未启用每日壁纸时使用)', null=True, upload_to='background/', verbose_name='背景图片/壁纸'),
        ),
    ]
