# Generated by Django 5.2.13 on 2026-05-09 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogsettings_bio_blogsettings_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('body', models.TextField(max_length=500, verbose_name='内容')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '留言板留言',
                'verbose_name_plural': '留言板留言',
                'ordering': ['-creation_time'],
            },
        ),
    ]
