# Generated by Django 5.2.13 on 2026-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_guestbookmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='文章封面图，用于列表页翻牌卡片展示（不设置则自动使用正文首图）', null=True, upload_to='article_covers/', verbose_name='cover image'),
        ),
    ]
